#!/usr/bin/env python
import re
import sys
import gzip


def extract_ips(file_path):
    ips = {}

    with gzip.open(file_path, "rb") as f:
        data = f.read()
        data = data.decode("utf-8")
        data = data.split("\n")

        for line in data:
            if "Failed password" in line:
                ip = re.search(r"from (.*?) port", line).group(1)
                if ip in ips:
                    ips[ip] += 1
                else:
                    ips[ip] = 1
    return ips

if __name__ == "__main__":
    file_path = sys.argv[1]

    ips = extract_ips(file_path)

    total = sum(ips.values())
    sorted_ips = sorted(ips.items(), key=lambda x: x[1])
    print("---------------------------------------------")
    print("|   Percent    |  Count |        IP         |")
    print("---------------------------------------------")
    for ip, count in sorted_ips:
        percent = (count / total) * 100
        print("|  {:8.4f}    | {:5d}  |  {:15s}  |".format(percent, count, ip))
    print("---------------------------------------------")
    print("|   Total      | {:5d}  |                   |".format(total))
    print("---------------------------------------------")
